@extends('layouts.app')
@section('title', $portal === 'admin' ? 'Đăng nhập quản trị' : 'Đăng nhập thí sinh')
@push('head')
<style>.unified-login{max-width:1000px;margin:38px auto;display:grid;grid-template-columns:1.05fr .95fr;overflow:hidden;padding:0}.login-cover{padding:43px;background:linear-gradient(145deg,#073b8c,#0b67dc);color:#fff;position:relative;overflow:hidden}.login-cover:after{content:"";position:absolute;width:250px;height:250px;background:#8b1538;border-radius:50%;right:-120px;bottom:-130px}.logo{width:62px;height:62px;border-radius:17px;background:#fff;color:#0b5ed7;display:grid;place-items:center;font-size:29px;font-weight:1000}.login-panel{padding:38px;background:#fff}.portal-tabs{display:grid;grid-template-columns:1fr 1fr;background:#eef2f7;padding:5px;border-radius:12px;margin-bottom:26px}.portal-tab{padding:11px;text-align:center;border-radius:9px;color:#64748b;font-weight:900}.portal-tab.active{background:#fff;color:#0b5ed7;box-shadow:0 3px 10px rgba(15,23,42,.1)}.portal-tab.admin.active{color:#8b1538}.login-panel .btn{width:100%;padding:14px}.login-field{margin-bottom:16px}.portal-note{font-size:13px;color:#64748b;border-top:1px solid #e2e8f0;padding-top:16px;margin-top:18px}@media(max-width:760px){.unified-login{grid-template-columns:1fr;margin:10px auto}.login-cover{padding:26px}.login-panel{padding:26px}.login-cover h1{font-size:27px!important}}</style>
@endpush
@section('content')
<div class="card unified-login"><section class="login-cover"><div class="logo">E</div><div style="font-size:12px;font-weight:900;letter-spacing:.16em;margin-top:25px;opacity:.8">ENGLISH OLYMPIC 2026</div><h1 style="font-size:38px;line-height:1.15;margin:12px 0">Một cổng đăng nhập<br>cho toàn hệ thống</h1><p style="line-height:1.7;opacity:.85">Thí sinh KET/PET và Ban tổ chức truy cập an toàn từ cùng một màn hình.</p><div class="row" style="margin-top:25px"><span class="badge" style="background:rgba(255,255,255,.16);color:#fff">KET · BLUE</span><span class="badge" style="background:#8b1538;color:#fff">PET · BURGUNDY</span></div></section><section class="login-panel"><div class="portal-tabs"><a class="portal-tab {{ $portal==='candidate'?'active':'' }}" href="{{ route('login') }}">Thí sinh</a><a class="portal-tab admin {{ $portal==='admin'?'active':'' }}" href="{{ route('login',['portal'=>'admin']) }}">Quản trị</a></div>
@if($portal === 'admin')<span class="badge" style="background:#fbeaf0;color:#8b1538">ADMIN PORTAL</span><h2 style="font-size:27px;margin:14px 0 7px">Đăng nhập quản trị</h2><p class="muted">Dành cho Ban tổ chức và giám khảo.</p><form method="post" action="{{ route('admin.login.submit') }}">@csrf<div class="login-field"><label>Email</label><input type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="username"></div><div class="login-field"><label>Mật khẩu</label><input type="password" name="password" required autocomplete="current-password"></div><label style="font-weight:500"><input type="checkbox" name="remember" value="1" style="width:auto"> Ghi nhớ đăng nhập</label><button class="btn" style="background:#8b1538;margin-top:16px">Vào trang quản trị →</button></form><div class="portal-note">🔒 Chỉ tài khoản có quyền admin/judge mới được truy cập.</div>
@else<span class="badge">CANDIDATE PORTAL</span><h2 style="font-size:27px;margin:14px 0 7px">Đăng nhập dự thi</h2><p class="muted">Nhập thông tin trên thẻ dự thi.</p><form method="post" action="{{ route('candidate.login.submit') }}">@csrf<div class="login-field"><label>Kỳ thi</label><select name="exam_selection" required @disabled($events->isEmpty())><option value="">-- Chọn kỳ thi KET hoặc PET --</option>@foreach($events as $event) @if($event->allow_ket)<option value="{{ $event->id }}:KET" @selected(old('exam_selection')===$event->id.':KET')>{{ $event->name }} — KET{{ $event->starts_at?' · '.$event->starts_at->format('H:i d/m/Y'):'' }}</option>@endif @if($event->allow_pet)<option value="{{ $event->id }}:PET" @selected(old('exam_selection')===$event->id.':PET')>{{ $event->name }} — PET{{ $event->starts_at?' · '.$event->starts_at->format('H:i d/m/Y'):'' }}</option>@endif @endforeach</select>@if($events->isEmpty())<div class="alert error" style="margin-top:10px">Hiện chưa có kỳ thi nào đang mở trong khung giờ này.</div>@endif</div><div class="login-field"><label>Số báo danh</label><input name="candidate_code" value="{{ old('candidate_code') }}" placeholder="Ví dụ: KET001 hoặc PET001" required autofocus autocomplete="username"></div><div class="login-field"><label>Mã PIN</label><input type="password" name="pin" placeholder="Nhập mã PIN" required autocomplete="current-password"></div><button class="btn">Vào khu vực làm bài →</button></form><div class="portal-note">🔒 Không chia sẻ mã PIN. Nếu thông tin sai, hãy báo giám thị.</div>@endif</section></div>
@endsection