@extends('layouts.app')
@section('title','Hoàn thành Round '.$round->round_order)
@section('body_class', strtoupper($candidate->level->code ?? 'KET') === 'PET' ? 'theme-pet' : 'theme-ket')
@section('topbar')
<div class="topbar"><div><div class="brand">ENGLISH OLYMPIC · {{ strtoupper($candidate->level->code ?? '') }}</div><div style="font-size:12px;opacity:.8">COMPUTER-BASED TEST</div></div><div class="nav"><span>{{ $candidate->candidate_code }} · {{ $candidate->full_name }}</span></div></div>
@endsection
@push('head')
<style>.stage-shell{max-width:1000px;margin:18px auto}.test-progress{display:flex;align-items:center;justify-content:center;margin:10px 0 30px}.stage{display:flex;align-items:center}.stage-circle{width:44px;height:44px;border-radius:50%;display:grid;place-items:center;background:#e2e8f0;color:#64748b;font-weight:1000}.stage.done .stage-circle{background:#14804a;color:#fff}.stage.current .stage-circle{background:var(--primary);color:#fff;box-shadow:0 0 0 6px var(--primary-soft)}.stage-label{font-size:12px;font-weight:900;margin-top:8px;text-align:center;color:#64748b}.stage-line{height:4px;width:100px;background:#e2e8f0;margin:0 12px 23px}.stage-line.done{background:#14804a}.completion-card{text-align:center;padding:42px;border-top:6px solid var(--primary)}.checkmark{width:84px;height:84px;border-radius:50%;background:#dcfce7;color:#14804a;display:grid;place-items:center;font-size:42px;font-weight:1000;margin:0 auto 20px}.round-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;max-width:620px;margin:25px auto}.round-summary div{background:#f8fafc;border:1px solid #e2e8f0;border-radius:13px;padding:15px}.round-summary strong{display:block;font-size:22px;margin-top:5px}.transition-box{max-width:700px;margin:20px auto 0;background:var(--primary-soft);border-radius:16px;padding:22px}.transition-box .btn{min-width:260px;padding:14px 24px;font-size:16px}.warning-box{background:#fff7ed;color:#9a3412;border:1px solid #fed7aa;border-radius:12px;padding:14px;margin:16px 0}.final-box{background:#ecfdf5;color:#166534;border-radius:14px;padding:20px;font-weight:700}@media(max-width:650px){.stage-line{width:35px}.completion-card{padding:25px 16px}.round-summary{grid-template-columns:1fr}.transition-box .btn{width:100%;min-width:0}}</style>
@endpush
@section('content')
<div class="stage-shell">
<div class="test-progress">@foreach($allRounds as $step)<div class="stage {{ $step->round_order < $round->round_order ? 'done' : ($step->id === $round->id ? 'current' : '') }}"><div><div class="stage-circle">{{ $step->round_order < $round->round_order ? '✓' : $step->round_order }}</div><div class="stage-label">ROUND {{ $step->round_order }}</div></div></div>@if(!$loop->last)<div class="stage-line {{ $step->round_order < $round->round_order ? 'done' : '' }}"></div>@endif @endforeach</div>
<section class="card completion-card"><div class="checkmark">✓</div><span class="badge">ROUND {{ $round->round_order }} COMPLETED</span><h1 style="font-size:32px;margin:15px 0 8px">Bạn đã hoàn thành Round {{ $round->round_order }}</h1><p class="muted">Bài làm đã được lưu và nộp thành công. Bạn không thể quay lại sửa đáp án của phần này.</p><div class="round-summary"><div><span class="muted">Đã trả lời</span><strong>{{ $attempt->answers()->count() }}/{{ $round->number_questions }}</strong></div><div><span class="muted">Thời gian làm</span><strong>{{ gmdate('i:s', (int) floor(($attempt->elapsed_ms ?? 0)/1000)) }}</strong></div><div><span class="muted">Trạng thái</span><strong style="font-size:16px">{{ $attempt->status === 'auto_submitted' ? 'Tự động nộp' : 'Đã nộp' }}</strong></div></div>
@if($nextRound)<div class="transition-box"><div class="muted" style="font-weight:800">NEXT SECTION</div><h2 style="margin:7px 0">Round {{ $nextRound->round_order }} · {{ $nextRound->name }}</h2><p>{{ $nextRound->number_questions }} câu · {{ floor($nextRound->time_limit_seconds/60) }} phút</p>@if($nextAttempt && $nextAttempt->status === 'in_progress')<a class="btn" href="{{ route('candidate.exam.show',[$nextRound,$nextAttempt]) }}">Tiếp tục Round {{ $nextRound->round_order }} →</a>@elseif($nextAttempt)<a class="btn" href="{{ route('candidate.exam.completed',[$nextRound,$nextAttempt]) }}">Xem phần đã hoàn thành →</a>@elseif($canStartNext)<div class="warning-box">Khi bấm bắt đầu, đồng hồ Round {{ $nextRound->round_order }} sẽ chạy ngay và không thể tạm dừng.</div><form method="post" action="{{ route('candidate.exam.start',$nextRound) }}">@csrf<button class="btn">Bắt đầu Round {{ $nextRound->round_order }} →</button></form>@else<div class="warning-box">Round {{ $nextRound->round_order }} chưa sẵn sàng. Trạng thái: {{ $nextRound->status === 'open' ? 'đề có '.$nextQuestionCount.'/'.$nextRound->number_questions.' câu' : 'chưa được mở' }}.</div><a class="btn secondary" href="{{ route('candidate.dashboard') }}">Về khu vực thí sinh</a>@endif</div>
@else<div class="final-box">Bạn đã hoàn thành toàn bộ bài thi English Olympic. Vui lòng giữ nguyên vị trí và làm theo hướng dẫn của giám thị.</div><a class="btn secondary" style="margin-top:18px" href="{{ route('candidate.dashboard') }}">Xem trạng thái bài thi</a>@endif
</section></div>
@endsection