@extends('layouts.app')
@section('title','Hồ sơ thi · '.$candidate->candidate_code)
@section('topbar') @include('admin.partials.nav') @endsection
@push('head')
<style>.profile-hero{background:linear-gradient(135deg,#071f49,#0b5ed7);color:#fff;border:0}.profile-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:rgba(255,255,255,.18);border-radius:13px;overflow:hidden;margin-top:22px}.profile-grid div{padding:14px;background:rgba(0,0,0,.08)}.profile-grid small{display:block;opacity:.7;margin-bottom:5px}.status-active{background:#dcfce7;color:#166534}.status-locked{background:#fee2e2;color:#991b1b}.status-finished{background:#e2e8f0;color:#475569}.round-status-card{border-top:5px solid #0b5ed7}.round-status-card.pet{border-top-color:#8b1538}.attempt-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.attempt-metrics div{background:#f8fafc;border-radius:10px;padding:12px}.attempt-metrics small{display:block;color:#64748b;margin-bottom:5px}.attempt-metrics strong{font-size:20px}.ready{color:#166534}.not-ready{color:#b42318}.danger-zone{border:1px solid #fecaca;background:#fff7f7;border-radius:12px;padding:14px;margin-top:15px}@media(max-width:700px){.profile-grid{grid-template-columns:1fr 1fr}.attempt-metrics{grid-template-columns:1fr}}</style>
@endpush
@section('content')
<a href="{{ route('admin.candidates.index') }}" class="muted">← Quay lại danh sách thí sinh</a>
<section class="card profile-hero" style="margin-top:15px"><div class="row between"><div><span class="badge" style="background:rgba(255,255,255,.16);color:#fff">{{ $candidate->level->code }} CANDIDATE</span><h1 style="font-size:32px;margin:13px 0 5px">{{ $candidate->full_name }}</h1><div style="opacity:.8">{{ $candidate->candidate_code }} · {{ $candidate->examEvent->name }}</div></div><span class="badge status-{{ $candidate->status }}">{{ $candidate->status==='active'?'ĐƯỢC PHÉP THI':($candidate->status==='locked'?'ĐÃ KHÓA THI':'ĐÃ HOÀN THÀNH') }}</span></div><div class="profile-grid"><div><small>Cấp độ</small><strong>{{ $candidate->level->code }}</strong></div><div><small>Lớp</small><strong>{{ $candidate->class_name ?: '—' }}</strong></div><div><small>Số máy</small><strong>{{ $candidate->computer_no ?: '—' }}</strong></div><div><small>Hoạt động cuối</small><strong>{{ optional($candidate->last_seen_at)->format('H:i:s') ?: 'Chưa online' }}</strong></div></div></section>
<div class="card"><div class="row between"><div><h2 style="margin-bottom:5px">Quyền dự thi</h2><div class="muted">Khóa sẽ đăng xuất thí sinh khỏi các trang thi trong lần truy cập tiếp theo.</div></div><div class="row">@if($candidate->status!=='active')<form method="post" action="{{ route('admin.candidates.allow-exam',$candidate) }}">@csrf<button class="btn success">✓ Cho phép dự thi</button></form>@else<form method="post" action="{{ route('admin.candidates.lock-exam',$candidate) }}" onsubmit="return confirm('Khóa quyền thi của {{ $candidate->candidate_code }}?')">@csrf<button class="btn danger">Khóa quyền thi</button></form>@endif<a class="btn secondary" href="{{ route('admin.candidates.index') }}?search={{ $candidate->candidate_code }}">Sửa thông tin</a></div></div></div>
<h2>Trạng thái từng Round</h2><div class="grid">@foreach($rounds as $round) @php($attempt=$round->attempt_record)<article class="card round-status-card {{ strtolower($candidate->level->code) }}"><div class="row between"><span class="badge">ROUND {{ $round->round_order }}</span><span class="badge">{{ $round->status==='open'?'ĐANG MỞ':($round->status==='closed'?'ĐÃ ĐÓNG':'CHỜ MỞ') }}</span></div><h3 style="margin:14px 0 5px">{{ $round->name }}</h3><div class="{{ $round->question_count >= $round->number_questions?'ready':'not-ready' }}" style="font-size:13px;font-weight:800">{{ $round->question_count >= $round->number_questions?'✓ Đề đã sẵn sàng':'⚠ Đề chưa đủ' }} · {{ $round->question_count }}/{{ $round->number_questions }} câu</div>
@if($attempt)<div class="attempt-metrics"><div><small>Đã trả lời</small><strong>{{ $attempt->answers_count }}/{{ $round->number_questions }}</strong></div><div><small>Điểm</small><strong>{{ $attempt->score ?? 0 }}</strong></div><div><small>Thời gian</small><strong>{{ $attempt->elapsed_ms ? gmdate('i:s',floor($attempt->elapsed_ms/1000)) : 'Đang chạy' }}</strong></div></div><p>Trạng thái: <span class="badge">{{ $attempt->status==='in_progress'?'ĐANG LÀM':($attempt->status==='auto_submitted'?'TỰ NỘP':'ĐÃ NỘP') }}</span></p><div class="danger-zone"><strong>Cho thi lại Round {{ $round->round_order }}</strong><p class="muted" style="font-size:13px;margin:5px 0 12px">Thao tác này xóa lượt thi, đáp án và kết quả hiện tại của riêng Round này.</p><form method="post" action="{{ route('admin.candidates.retake',[$candidate,$round]) }}" onsubmit="return confirm('Cho {{ $candidate->candidate_code }} thi lại Round {{ $round->round_order }}? Toàn bộ đáp án và kết quả Round này sẽ bị xóa.')">@csrf<button class="btn danger">Cho thi lại Round {{ $round->round_order }}</button></form></div>
@else<div style="padding:25px 0;text-align:center"><div class="muted">Chưa bắt đầu Round này</div>@if($candidate->status==='active'&&$round->status==='open'&&$round->question_count >= $round->number_questions)<div class="ready" style="font-weight:800;margin-top:8px">Thí sinh đã được phép bắt đầu</div>@else<div class="not-ready" style="font-weight:800;margin-top:8px">Chưa thể bắt đầu</div>@endif</div>@endif</article>@endforeach</div>
@endsection