@extends('layouts.app')
@section('title','Tổng quan kỳ thi')
@section('topbar') @include('admin.partials.nav') @endsection
@push('head')
<style>.hero{background:linear-gradient(135deg,#071f49,#0b5ed7);color:#fff;border:0}.event-picker{min-width:290px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.stat{margin:0;border-top:4px solid var(--primary)}.stat strong{font-size:32px;display:block;margin-top:7px}.stat.online{border-color:#16a34a}.rounds{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.round-card{margin:0;border-top:5px solid var(--primary)}.round-numbers{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}.round-numbers div{background:#f8fafc;padding:10px;border-radius:10px}.rank-medal{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#e2e8f0;font-weight:900}.rank-1{background:#fbbf24}.rank-2{background:#cbd5e1}.rank-3{background:#d6a16f}.score{font-size:20px;font-weight:900;color:var(--primary)}@media(max-width:900px){.stats,.rounds{grid-template-columns:1fr 1fr}}@media(max-width:600px){.stats,.rounds{grid-template-columns:1fr}}</style>
@endpush
@section('content')
@if(!$event)<div class="alert error">Chưa có kỳ thi.</div>@else
<div class="card hero"><div class="row between"><div><span class="badge" style="background:rgba(255,255,255,.16);color:#fff">TRUNG TÂM ĐIỀU HÀNH</span><h1 style="font-size:34px;margin:13px 0 5px">{{ $event->name }}</h1><p style="opacity:.82;margin:0">Theo dõi vận hành, tiến độ và kết quả tại một nơi.</p></div><form method="get" class="event-picker"><label style="color:#fff">Kỳ thi đang xem</label><select name="event_id" onchange="this.form.submit()">@foreach($events as $item)<option value="{{ $item->id }}" @selected($item->id===$event->id)>{{ $item->name }} · {{ $item->status }}</option>@endforeach</select></form></div></div>
<div class="stats"><div class="card stat"><span class="muted">Tổng thí sinh</span><strong>{{ $candidateCount }}</strong></div><div class="card stat online"><span class="muted">Online trong 2 phút</span><strong>{{ $onlineCount }}</strong></div><div class="card stat"><span class="muted">Đang làm bài</span><strong>{{ $workingCount }}</strong></div><div class="card stat"><span class="muted">Lượt đã nộp</span><strong>{{ $submittedCount }}</strong></div></div>
<div class="card"><div class="row between"><div><h2 style="margin:0 0 5px">Điều khiển kỳ thi</h2><span class="muted">Mở hoặc đóng các Round của kỳ thi.</span></div><div class="row"><form method="post" action="{{ route('admin.rounds.open-all') }}">@csrf<input type="hidden" name="event_id" value="{{ $event->id }}"><button class="btn success">▶ Mở tất cả</button></form><form method="post" action="{{ route('admin.rounds.close-all') }}">@csrf<input type="hidden" name="event_id" value="{{ $event->id }}"><button class="btn danger">■ Đóng tất cả</button></form></div></div></div>
<div class="rounds">@foreach($rounds as $round)<article class="card round-card"><div class="row between"><span class="badge">ROUND {{ $round->round_order }}</span><span class="badge">{{ $round->status==='open'?'ĐANG MỞ':($round->status==='closed'?'ĐÃ ĐÓNG':'CHỜ MỞ') }}</span></div><h3 style="margin:14px 0 4px">{{ $round->name }}</h3><div class="muted">{{ $round->number_questions }} câu · {{ floor($round->time_limit_seconds/60) }} phút</div><div class="round-numbers"><div>Đang làm<br><strong>{{ $round->working_count }}</strong></div><div>Đã nộp<br><strong>{{ $round->submitted_count }}</strong></div></div><div class="row">@if($round->status!=='open')<form method="post" action="{{ route('admin.rounds.open',$round) }}">@csrf<button class="btn">Mở Round</button></form>@else<form method="post" action="{{ route('admin.rounds.close',$round) }}">@csrf<button class="btn danger">Đóng Round</button></form>@endif<a class="btn secondary" href="{{ route('admin.rounds.results',$round) }}">Kết quả</a></div></article>@endforeach</div>
<div class="card"><div class="row between"><div><h2 style="margin:0 0 5px">Top thí sinh theo tổng điểm</h2><span class="muted">Cộng điểm các Round đã hoàn thành; hòa điểm xếp theo tổng thời gian thấp hơn.</span></div><div class="row"><a class="btn" href="{{ route('admin.rankings',['event_id'=>$event->id]) }}">Xem toàn bộ xếp hạng →</a><a class="btn success" style="background:#16803c" href="{{ route('admin.rankings.export',['event_id'=>$event->id]) }}">⬇ Tải Excel</a></div></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Hạng</th><th>Thí sinh</th><th>Cấp</th><th>Round hoàn thành</th><th>Đúng</th><th>Tổng điểm</th><th>Tổng thời gian</th></tr></thead><tbody>@forelse($leaderboard as $index=>$candidate)<tr><td><span class="rank-medal rank-{{ $index+1 }}">{{ $index+1 }}</span></td><td><strong>{{ $candidate->candidate_code }}</strong><br><span class="muted">{{ $candidate->full_name }}</span></td><td>{{ $candidate->level->code }}</td><td>{{ $candidate->rounds_completed }}/{{ $rounds->count() }}</td><td>{{ $candidate->total_correct }}</td><td class="score">{{ number_format($candidate->total_score,2) }}</td><td>{{ gmdate('H:i:s',(int)($candidate->total_elapsed/1000)) }}</td></tr>@empty<tr><td colspan="7" class="muted">Chưa có bài thi đã nộp.</td></tr>@endforelse</tbody></table></div></div>
@endif
@endsection