@extends('layouts.app')
@section('title','Trung tâm điều hành')
@section('topbar') @include('admin.partials.nav') @endsection
@push('head')
<style>.admin-hero{background:linear-gradient(135deg,#071f49,#0b5ed7);color:#fff;border:0}.stat{border-left:5px solid #0b5ed7}.stat.online{border-color:#16a34a}.stat strong{font-size:32px;display:block;margin-top:5px}.control-strip{display:flex;gap:10px;flex-wrap:wrap}.round-admin{border-top:4px solid #0b5ed7}.status-open{background:#dcfce7;color:#166534}.status-closed{background:#fee2e2;color:#991b1b}.monitor td{font-size:14px}.progress-mini{height:7px;background:#e2e8f0;border-radius:99px;overflow:hidden;min-width:100px}.progress-mini i{display:block;height:100%;background:#0b5ed7}.ket-label{color:#0b5ed7;font-weight:900}.pet-label{color:#8b1538;font-weight:900}</style>
@endpush
@section('content')
@if(!$event)<div class="alert error">Chưa có kỳ thi.</div>@else
<div class="card admin-hero"><span class="badge" style="background:rgba(255,255,255,.15);color:#fff">ĐANG VẬN HÀNH</span><h1 style="font-size:32px;margin:13px 0 6px">{{ $event->name }}</h1><p style="opacity:.8;margin:0">Theo dõi thí sinh, điều khiển Round và quản lý đề thi tại một nơi.</p></div>
<div class="grid"><div class="card stat"><span class="muted">Tổng thí sinh</span><strong>{{ $candidateCount }}</strong></div><div class="card stat online"><span class="muted">Online trong 2 phút</span><strong>{{ $onlineCount }}</strong></div><div class="card stat"><span class="muted">Đang làm bài</span><strong>{{ $attempts->where('status','in_progress')->count() }}</strong></div><div class="card stat"><span class="muted">Đã nộp bài</span><strong>{{ $attempts->whereIn('status',['submitted','auto_submitted'])->count() }}</strong></div></div>
<div class="card"><div class="row between"><div><h2 style="margin-bottom:5px">Điều khiển kỳ thi</h2><div class="muted">Mở đồng thời toàn bộ Round hoặc điều khiển riêng từng vòng.</div></div><div class="control-strip"><form method="post" action="{{ route('admin.rounds.open-all') }}">@csrf<button class="btn success">▶ Mở tất cả Round</button></form><form method="post" action="{{ route('admin.rounds.close-all') }}">@csrf<button class="btn danger">■ Đóng tất cả Round</button></form></div></div></div>
<div class="grid">@foreach($rounds as $round)<div class="card round-admin"><div class="row between"><span class="badge">ROUND {{ $round->round_order }}</span><span class="badge {{ $round->status==='open'?'status-open':'status-closed' }}">{{ $round->status==='open'?'ĐANG MỞ':'ĐANG ĐÓNG' }}</span></div><h3 style="margin:15px 0 5px">{{ $round->name }}</h3><p class="muted">{{ $round->number_questions }} câu · {{ floor($round->time_limit_seconds/60) }} phút</p><div class="row" style="margin:16px 0"><span>Đang làm: <strong>{{ $round->working_count }}</strong></span><span>Đã nộp: <strong>{{ $round->submitted_count }}</strong></span></div><div class="row">@if($round->status!=='open')<form method="post" action="{{ route('admin.rounds.open',$round) }}">@csrf<button class="btn">Mở Round</button></form>@else<form method="post" action="{{ route('admin.rounds.close',$round) }}">@csrf<button class="btn danger">Đóng Round</button></form>@endif<a class="btn secondary" href="{{ route('admin.rounds.results',$round) }}">Kết quả</a></div></div>@endforeach</div>
<div class="card"><div class="row between"><div><h2 style="margin-bottom:5px">Theo dõi bài làm trực tiếp</h2><div class="muted">Xem tiến độ từng thí sinh trên trang giám sát riêng.</div></div><a class="btn" href="{{ route('admin.monitor') }}">Mở trang theo dõi LIVE →</a></div></div>
@endif
@endsection