@extends('layouts.app')
@section('title','Theo dõi bài thi trực tiếp')
@section('topbar') @include('admin.partials.nav') @endsection
@push('head')
<style>.live-head{background:linear-gradient(135deg,#052e2b,#087f5b);color:#fff;border:0}.live-dot{display:inline-block;width:11px;height:11px;border-radius:50%;background:#4ade80;box-shadow:0 0 0 6px rgba(74,222,128,.2);margin-right:9px}.monitor-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.monitor-stats .card{margin:0}.monitor-stats strong{font-size:31px;display:block;margin-top:5px}.monitor-filter{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px}.progress-mini{height:8px;background:#e2e8f0;border-radius:99px;overflow:hidden;margin-top:7px;min-width:120px}.progress-mini i{display:block;height:100%;background:var(--primary)}.status-working{background:#dcfce7;color:#166534}.status-done{background:#eaf3ff;color:#0b5ed7}.status-auto{background:#fff7ed;color:#9a3412}.score-live{font-weight:900;color:var(--primary)}@media(max-width:850px){.monitor-filter,.monitor-stats{grid-template-columns:1fr}}</style>
@endpush
@section('content')
<div class="card live-head"><div class="row between"><div><div style="font-weight:900;letter-spacing:.1em"><span class="live-dot"></span>THEO DÕI TRỰC TIẾP</div><h1 style="font-size:32px;margin:13px 0 6px">Tiến độ làm bài của thí sinh</h1><p style="opacity:.82;margin:0">Tự động cập nhật sau mỗi 5 giây · {{ $event->name ?? 'Chưa chọn kỳ thi' }}</p></div><div><div class="muted" style="color:#d1fae5">Cập nhật lúc</div><strong id="lastUpdate">{{ now()->format('H:i:s') }}</strong></div></div></div>
<div class="monitor-stats"><div class="card"><span class="muted">Đang làm bài</span><strong>{{ $working }}</strong></div><div class="card"><span class="muted">Đã nộp / tự nộp</span><strong>{{ $submitted }}</strong></div><div class="card"><span class="muted">Tổng lượt phù hợp bộ lọc</span><strong>{{ $attempts->total() }}</strong></div></div>
<div class="card" style="margin-top:18px"><form class="monitor-filter" method="get"><select name="event_id"><option value="">Kỳ thi đang hoạt động</option>@foreach($events as $item)<option value="{{ $item->id }}" @selected(optional($event)->id===$item->id)>{{ $item->name }}</option>@endforeach</select><select name="round_id"><option value="">Tất cả Round</option>@foreach($rounds as $round)<option value="{{ $round->id }}" @selected(request('round_id')==$round->id)>Round {{ $round->round_order }}</option>@endforeach</select><select name="level_id"><option value="">Tất cả cấp độ</option>@foreach($levels as $level)<option value="{{ $level->id }}" @selected(request('level_id')==$level->id)>{{ $level->code }}</option>@endforeach</select><select name="status"><option value="">Mọi trạng thái</option><option value="in_progress" @selected(request('status')==='in_progress')>Đang làm</option><option value="submitted" @selected(request('status')==='submitted')>Đã nộp</option><option value="auto_submitted" @selected(request('status')==='auto_submitted')>Tự nộp</option></select><button class="btn">Áp dụng</button></form></div>
<div class="card table-wrap"><table><thead><tr><th>Thí sinh</th><th>Cấp</th><th>Round</th><th>Tiến độ</th><th>Trạng thái</th><th>Điểm</th><th>Hạng Round</th><th>Bắt đầu</th><th>Cập nhật</th></tr></thead><tbody>@forelse($attempts as $a)<tr><td><strong>{{ $a->candidate->candidate_code }}</strong><br><span class="muted">{{ $a->candidate->full_name }}</span></td><td><span class="badge">{{ $a->candidate->level->code }}</span></td><td><strong>Round {{ $a->round->round_order }}</strong></td><td><strong>{{ $a->answers_count }}/{{ $a->round->number_questions }}</strong><div class="progress-mini"><i style="width:{{ min(100,$a->answers_count/max(1,$a->round->number_questions)*100) }}%"></i></div></td><td><span class="badge {{ $a->status==='in_progress'?'status-working':($a->status==='auto_submitted'?'status-auto':'status-done') }}">{{ $a->status==='in_progress'?'ĐANG LÀM':($a->status==='auto_submitted'?'TỰ NỘP':'ĐÃ NỘP') }}</span></td><td class="score-live">{{ $a->status==='in_progress'?'—':number_format((float)$a->score,2) }}</td><td>{{ $a->rank ? '#'.$a->rank : '—' }}</td><td>{{ optional($a->started_at)->format('H:i:s') }}</td><td>{{ optional($a->updated_at)->format('H:i:s') }}</td></tr>@empty<tr><td colspan="9" class="muted">Chưa có lượt thi phù hợp.</td></tr>@endforelse</tbody></table>{{ $attempts->links() }}</div>
<script>setTimeout(()=>location.reload(),5000)</script>
@endsection