@extends('layouts.app')
@section('title','Theo dõi bài làm trực tiếp')
@section('topbar') @include('admin.partials.nav') @endsection
@push('head')
<style>.live-head{background:linear-gradient(135deg,#071f49,#0b5ed7);color:#fff;border:0}.live-dot{display:inline-block;width:10px;height:10px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 5px rgba(34,197,94,.2);margin-right:8px}.monitor-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.monitor-stats .card{margin:0}.monitor-stats strong{font-size:30px;display:block;margin-top:5px}.monitor-filter{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px}.progress-mini{height:8px;background:#e2e8f0;border-radius:99px;overflow:hidden;margin-top:7px;min-width:120px}.progress-mini i{display:block;height:100%;background:#0b5ed7}.ket-text{color:#0b5ed7;font-weight:900}.pet-text{color:#8b1538;font-weight:900}.status-working{background:#dcfce7;color:#166534}.status-done{background:#eaf3ff;color:#0b5ed7}@media(max-width:850px){.monitor-filter{grid-template-columns:1fr}.monitor-stats{grid-template-columns:1fr}}</style>
@endpush
@section('content')
<div class="card live-head"><div class="row between"><div><div style="font-weight:900;letter-spacing:.1em"><span class="live-dot"></span>LIVE MONITORING</div><h1 style="font-size:32px;margin:13px 0 6px">Theo dõi bài làm trực tiếp</h1><p style="opacity:.8;margin:0">Tự động cập nhật sau mỗi 5 giây · {{ $event->name ?? 'Chưa chọn kỳ thi' }}</p></div><div id="lastUpdate" style="opacity:.8">{{ now()->format('H:i:s') }}</div></div></div>
<div class="monitor-stats"><div class="card"><span class="muted">Đang làm bài</span><strong>{{ $working }}</strong></div><div class="card"><span class="muted">Đã nộp</span><strong>{{ $submitted }}</strong></div><div class="card"><span class="muted">Lượt thi hiển thị</span><strong>{{ $attempts->total() }}</strong></div></div>
<div class="card" style="margin-top:18px"><form class="monitor-filter" method="get"><select name="event_id"><option value="">Kỳ thi đang hoạt động</option>@foreach($events as $item)<option value="{{ $item->id }}" @selected(optional($event)->id===$item->id)>{{ $item->name }} · {{ $item->allow_ket?'KET':'PET' }}</option>@endforeach</select><select name="round_id"><option value="">Tất cả Round</option>@foreach($rounds as $round)<option value="{{ $round->id }}" @selected(request('round_id')==$round->id)>Round {{ $round->round_order }}</option>@endforeach</select><select name="level_id"><option value="">KET & PET</option>@foreach($levels as $level)<option value="{{ $level->id }}" @selected(request('level_id')==$level->id)>{{ $level->code }}</option>@endforeach</select><select name="status"><option value="">Mọi trạng thái</option><option value="in_progress" @selected(request('status')==='in_progress')>Đang làm</option><option value="submitted" @selected(request('status')==='submitted')>Đã nộp</option><option value="auto_submitted" @selected(request('status')==='auto_submitted')>Tự nộp</option></select><button class="btn">Lọc</button></form></div>
<div class="card table-wrap"><table><thead><tr><th>Thí sinh</th><th>Cấp</th><th>Round</th><th>Tiến độ</th><th>Trạng thái</th><th>Bắt đầu</th><th>Cập nhật</th></tr></thead><tbody>@forelse($attempts as $a)<tr><td><strong>{{ $a->candidate->candidate_code }}</strong><br><span class="muted">{{ $a->candidate->full_name }}</span></td><td class="{{ $a->candidate->level->code==='PET'?'pet-text':'ket-text' }}">{{ $a->candidate->level->code }}</td><td><strong>Round {{ $a->round->round_order }}</strong></td><td><strong>{{ $a->answers_count }}/{{ $a->round->number_questions }}</strong><div class="progress-mini"><i style="width:{{ min(100,$a->answers_count/max(1,$a->round->number_questions)*100) }}%"></i></div></td><td><span class="badge {{ $a->status==='in_progress'?'status-working':'status-done' }}">{{ $a->status==='in_progress'?'ĐANG LÀM':($a->status==='auto_submitted'?'TỰ NỘP':'ĐÃ NỘP') }}</span></td><td>{{ optional($a->started_at)->format('H:i:s') }}</td><td>{{ optional($a->updated_at)->format('H:i:s') }}</td></tr>@empty<tr><td colspan="7" class="muted">Chưa có lượt thi phù hợp.</td></tr>@endforelse</tbody></table>{{ $attempts->links() }}</div>
<script>setTimeout(()=>location.reload(),5000)</script>
@endsection