@extends('layouts.app')
@section('title','Ngân hàng câu hỏi')
@section('topbar') @include('admin.partials.nav') @endsection
@push('head')
<style>.level-tabs{display:flex;gap:10px;margin-bottom:18px}.level-tab{padding:11px 22px;border-radius:11px;background:#fff;border:2px solid #dbe4f0;font-weight:900}.level-tab.active,.level-tab:hover{background:#0b5ed7;color:#fff;border-color:#0b5ed7}.level-tab.pet.active{background:#8b1538;border-color:#8b1538}.question-form details{margin-top:15px}.media-preview{max-width:150px;max-height:90px;border-radius:8px}.question-item{border-left:5px solid #0b5ed7}.question-item.pet{border-left-color:#8b1538}.question-copy{max-width:520px;line-height:1.5}.actions{display:flex;gap:7px;flex-wrap:wrap}.bulk-toolbar{display:flex;gap:12px;align-items:center;background:#fff;border:1px solid #dbe4f0;border-radius:13px;padding:12px 16px}.select-box{width:20px;height:20px;accent-color:#0b5ed7;cursor:pointer}.question-head{display:flex;gap:12px;align-items:center}.edit-panel{margin-top:16px;padding:18px;background:#f8fafc;border-radius:13px}.asset{font-size:12px;color:#0b5ed7;font-weight:700}.filter-bar{display:grid;grid-template-columns:1fr 1fr 2fr auto;gap:10px}.choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:750px){.filter-bar,.choice-grid{grid-template-columns:1fr}}</style>
@endpush
@section('content')
<div class="row between"><div><h1 style="margin-bottom:5px">Ngân hàng câu hỏi</h1><p class="muted">Tạo và quản lý riêng đề KET/PET theo từng Round.</p></div><span class="badge">{{ $questions->total() }} CÂU HỎI</span></div>
<div class="level-tabs"><a class="level-tab {{ !request('level_id')?'active':'' }}" href="{{ route('admin.questions.index') }}">Tất cả</a>@foreach($levels as $l)<a class="level-tab {{ strtolower($l->code) }} {{ request('level_id')==$l->id?'active':'' }}" href="{{ route('admin.questions.index',['level_id'=>$l->id]) }}">{{ $l->code }}</a>@endforeach</div>
<div class="card"><form class="filter-bar" method="get"><select name="level_id"><option value="">Tất cả cấp độ</option>@foreach($levels as $l)<option value="{{ $l->id }}" @selected(request('level_id')==$l->id)>{{ $l->code }}</option>@endforeach</select><select name="round_id"><option value="">Tất cả Round</option>@foreach($rounds as $r)<option value="{{ $r->id }}" @selected(request('round_id')==$r->id)>Round {{ $r->round_order }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" placeholder="Tìm nội dung câu hỏi..."><button class="btn">Lọc dữ liệu</button></form></div>
<div class="card question-form"><div class="row between"><div><h2 style="margin-bottom:5px">Tạo câu hỏi mới</h2><div class="muted">Có thể thêm bài đọc, ảnh minh họa hoặc file nghe.</div></div><span class="badge">NEW</span></div><form method="post" enctype="multipart/form-data" action="{{ route('admin.questions.store') }}">@csrf
<div class="grid"><div><label>Cấp độ</label><select name="level_id" required>@foreach($levels as $l)<option value="{{ $l->id }}">{{ $l->code }}</option>@endforeach</select></div><div><label>Round</label><select name="round_id"><option value="">Chưa gán</option>@foreach($rounds as $r)<option value="{{ $r->id }}">Round {{ $r->round_order }} · {{ $r->name }}</option>@endforeach</select></div><div><label>Phần thi</label><select name="category_id"><option value="">General</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div><label>Loại câu</label><select name="question_type"><option value="single_choice">Trắc nghiệm / Reading</option><option value="listening_single_choice">Listening</option></select></div></div>
<div style="margin-top:14px"><label>Bài đọc (nếu là Reading)</label><textarea name="passage_text" placeholder="Dán đoạn văn bài đọc tại đây. Khi thi, bài đọc ở bên trái và câu hỏi ở bên phải."></textarea></div><div style="margin-top:14px"><label>Nội dung câu hỏi</label><textarea name="question_text" required placeholder="Nhập câu hỏi..."></textarea></div>
<div class="choice-grid"><div><label>Đáp án A</label><input name="option_a" required></div><div><label>Đáp án B</label><input name="option_b" required></div><div><label>Đáp án C</label><input name="option_c" required></div><div><label>Đáp án D</label><input name="option_d" required></div></div>
<div class="grid" style="margin-top:14px"><div><label>Đáp án đúng</label><select name="correct_option"><option>A</option><option>B</option><option>C</option><option>D</option></select></div><div><label>Điểm</label><input type="number" step="0.25" min="0.25" name="points" value="1"></div><div><label>Thứ tự trong Round</label><input type="number" name="sort_order" min="1" value="1"></div><div><input type="hidden" name="is_active" value="0"><label><input style="width:auto" type="checkbox" name="is_active" value="1" checked> Đang bật</label></div></div>
<div class="grid" style="margin-top:14px"><div><label>Ảnh minh họa (JPG/PNG/WebP, tối đa 5MB)</label><input type="file" name="image" accept="image/*"></div><div><label>File nghe (MP3/WAV/OGG/M4A, tối đa 15MB)</label><input type="file" name="audio" accept="audio/*"></div></div><button class="btn" style="margin-top:17px">+ Tạo và gán câu hỏi</button></form></div>
<div class="row between" style="margin:24px 0 12px"><h2 style="margin:0">Danh sách câu hỏi</h2><div class="bulk-toolbar"><label style="margin:0;display:flex;align-items:center;gap:8px"><input id="selectAllQuestions" class="select-box" type="checkbox"> Chọn tất cả trang này</label><form id="bulkDeleteForm" method="post" action="{{ route('admin.questions.bulk-destroy') }}" onsubmit="return confirm('Xóa toàn bộ câu hỏi đã chọn? Dữ liệu và file media liên quan sẽ bị xóa.')">@csrf @method('DELETE')<button id="bulkDeleteButton" class="btn danger" disabled>Xóa đã chọn (<span id="selectedCount">0</span>)</button></form></div></div>
@forelse($questions as $q)<article class="card question-item {{ strtolower($q->level->code) }}"><div class="row between"><div class="question-head"><input class="select-box question-select" type="checkbox" name="question_ids[]" value="{{ $q->id }}" form="bulkDeleteForm"><div class="row"><span class="badge">{{ $q->level->code }}</span><span class="badge">{{ $q->roundAssignments->map(fn($a)=>'ROUND '.$a->round->round_order)->join(', ') ?: 'CHƯA GÁN ROUND' }}</span><span class="badge">{{ $q->is_active?'ĐANG BẬT':'ĐANG TẮT' }}</span></div></div><strong>#{{ $q->id }}</strong></div><div class="question-copy"><h3 style="margin:15px 0 8px">{{ $q->question_text }}</h3>@if($q->passage_text)<div class="asset">📖 Có bài đọc</div>@endif @if($q->image_path)<div class="asset">🖼 Có ảnh</div>@endif @if($q->audio_path)<div class="asset">🔊 Có file nghe</div>@endif <ol type="A">@foreach($q->options as $o)<li>{{ $o->option_text }}</li>@endforeach</ol></div><div class="actions"><button class="btn secondary" type="button" onclick="document.getElementById('edit-{{ $q->id }}').hidden=!document.getElementById('edit-{{ $q->id }}').hidden">Sửa câu hỏi</button><form method="post" action="{{ route('admin.questions.destroy',$q) }}" onsubmit="return confirm('Xóa câu hỏi này?')">@csrf @method('DELETE')<button class="btn danger">Xóa</button></form></div>
<div id="edit-{{ $q->id }}" class="edit-panel" hidden><form method="post" enctype="multipart/form-data" action="{{ route('admin.questions.update',$q) }}">@csrf @method('PUT')<div class="grid"><div><label>Cấp</label><select name="level_id">@foreach($levels as $l)<option value="{{ $l->id }}" @selected($q->level_id==$l->id)>{{ $l->code }}</option>@endforeach</select></div><div><label>Round</label><select name="round_id"><option value="">Chưa gán</option>@foreach($rounds as $r)<option value="{{ $r->id }}" @selected($q->roundAssignments->contains('round_id',$r->id))>Round {{ $r->round_order }}</option>@endforeach</select></div><div><label>Phần thi</label><select name="category_id"><option value="">General</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected($q->category_id==$c->id)>{{ $c->name }}</option>@endforeach</select></div><div><label>Loại</label><select name="question_type"><option value="single_choice" @selected($q->question_type==='single_choice')>Trắc nghiệm / Reading</option><option value="listening_single_choice" @selected($q->question_type==='listening_single_choice')>Listening</option></select></div></div><label style="margin-top:12px">Bài đọc</label><textarea name="passage_text">{{ $q->passage_text }}</textarea><label style="margin-top:12px">Câu hỏi</label><textarea name="question_text" required>{{ $q->question_text }}</textarea><div class="choice-grid">@foreach(['A','B','C','D'] as $code) @php($opt=$q->options->firstWhere('option_code',$code))<div><label>Đáp án {{ $code }}</label><input name="option_{{ strtolower($code) }}" value="{{ $opt->option_text ?? '' }}" required></div>@endforeach</div><div class="grid" style="margin-top:12px"><div><label>Đúng</label><select name="correct_option">@foreach(['A','B','C','D'] as $code)<option @selected(optional($q->options->firstWhere('option_code',$code))->is_correct)>{{ $code }}</option>@endforeach</select></div><div><label>Điểm</label><input type="number" step=".25" name="points" value="{{ $q->points }}"></div><div><label>Thứ tự</label><input type="number" name="sort_order" value="{{ optional($q->roundAssignments->first())->sort_order ?? 1 }}"></div><div><input type="hidden" name="is_active" value="0"><label><input style="width:auto" type="checkbox" name="is_active" value="1" @checked($q->is_active)> Đang bật</label></div></div><div class="grid" style="margin-top:12px"><div><label>Thay ảnh</label><input type="file" name="image" accept="image/*"></div><div><label>Thay audio</label><input type="file" name="audio" accept="audio/*"></div></div><button class="btn" style="margin-top:14px">Lưu thay đổi</button></form></div></article>@empty<div class="card muted">Không có câu hỏi phù hợp bộ lọc.</div>@endforelse
{{ $questions->links() }}
<script>
const selectAll=document.getElementById('selectAllQuestions'), boxes=[...document.querySelectorAll('.question-select')], deleteButton=document.getElementById('bulkDeleteButton'), count=document.getElementById('selectedCount');
function updateSelection(){const selected=boxes.filter(box=>box.checked).length;count.textContent=selected;deleteButton.disabled=selected===0;if(selectAll){selectAll.checked=boxes.length>0&&selected===boxes.length;selectAll.indeterminate=selected>0&&selected<boxes.length;}}
selectAll?.addEventListener('change',()=>{boxes.forEach(box=>box.checked=selectAll.checked);updateSelection()});boxes.forEach(box=>box.addEventListener('change',updateSelection));updateSelection();
</script>
@endsection