@extends('layouts.app')
@section('title','Tổng hợp điểm và xếp hạng')
@section('topbar') @include('admin.partials.nav') @endsection
@push('head')
<style>.ranking-hero{background:linear-gradient(135deg,#3b1020,#8b1538);color:#fff;border:0}.filters{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:end}.podium{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.podium-card{text-align:center;margin:0;border-top:5px solid #cbd5e1}.podium-card:first-child{border-color:#fbbf24}.place{font-size:34px;font-weight:1000}.total-score{font-size:25px;font-weight:1000;color:var(--primary)}.round-score{white-space:nowrap}.rank-cell{font-size:20px;font-weight:1000}@media(max-width:700px){.podium{grid-template-columns:1fr}.filters{grid-template-columns:1fr}}</style>
@endpush
@section('content')
<div class="card ranking-hero"><div class="row between"><div><span class="badge" style="background:rgba(255,255,255,.15);color:#fff">LEADERBOARD</span><h1 style="font-size:33px;margin:13px 0 5px">Tổng hợp điểm và xếp hạng</h1></div><form method="get" class="filters"><select name="event_id" onchange="this.form.submit()">@foreach($events as $item)<option value="{{ $item->id }}" @selected(optional($event)->id===$item->id)>{{ $item->name }}</option>@endforeach</select><noscript><button class="btn">Xem</button></noscript></form></div></div>
@if($event)<div class="podium">@foreach($rankings->take(3) as $candidate)<div class="card podium-card"><div class="place">#{{ $candidate->overall_rank }}</div><h3 style="margin:8px 0 4px">{{ $candidate->full_name }}</h3><div class="muted">{{ $candidate->candidate_code }} · {{ $candidate->level->code }}</div><div class="total-score" style="margin-top:12px">{{ number_format($candidate->total_score,2) }} điểm</div></div>@endforeach</div>
<div class="card"><div class="row between"><div><h2 style="margin:0 0 5px">Xuất kết quả</h2><span class="muted">Tải toàn bộ điểm và thứ hạng của kỳ thi đang chọn.</span></div><a class="btn success" style="background:#16803c;font-size:16px" href="{{ route('admin.rankings.export',['event_id'=>$event->id]) }}">⬇ TẢI FILE EXCEL</a></div></div><div class="card table-wrap"><table><thead><tr><th>Hạng</th><th>SBD / Họ tên</th><th>Cấp</th><th>Round 1</th><th>Round 2</th><th>Round 3</th><th>Đúng</th><th>Sai</th><th>Tổng điểm</th><th>Thời gian</th></tr></thead><tbody>@forelse($rankings as $candidate)<tr><td class="rank-cell">#{{ $candidate->overall_rank }}</td><td><strong>{{ $candidate->candidate_code }}</strong><br><span class="muted">{{ $candidate->full_name }}</span></td><td><span class="badge">{{ $candidate->level->code }}</span></td>@foreach([1,2,3] as $order) @php($attempt=$candidate->attempts->first(fn($a)=>optional($a->round)->round_order===$order))<td class="round-score">{{ $attempt ? number_format((float)$attempt->score,2) : '—' }}</td>@endforeach<td>{{ $candidate->total_correct }}</td><td>{{ $candidate->total_wrong }}</td><td class="total-score">{{ number_format($candidate->total_score,2) }}</td><td>{{ $candidate->total_elapsed ? gmdate('H:i:s',(int)($candidate->total_elapsed/1000)) : '—' }}</td></tr>@empty<tr><td colspan="10" class="muted">Chưa có thí sinh hoặc kết quả thi.</td></tr>@endforelse</tbody></table></div>
<div class="alert ok">Bảng xếp hạng chỉ cộng các bài đã nộp hoặc được hệ thống tự nộp. Thí sinh chưa thi vẫn hiển thị với 0 điểm.</div>@endif
@endsection